// modded compat for enchanting apparatus books, no treasure enchants included
// still need to add these mods: spartanweaponry, spartanshields, galosphere

ServerEvents.recipes((event) => {
    let recipes = [
        {
            inputs: [
                "2x forbidden_arcanus:arcane_crystal_block",
                "2x ars_nouveau:source_gem_block",
                "4x iceandfire:stymphalian_bird_feather",
            ],
            enchantment: "ensorcellation:air_affinity",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "ars_nouveau:source_gem_block",
                "#forge:ingots/silver",
            ],
            enchantment: "ensorcellation:quick_draw",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "2x ars_nouveau:source_gem_block",
                "2x #forge:ingots/silver",
            ],
            enchantment: "ensorcellation:quick_draw",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "2x ars_nouveau:source_gem_block",
                "2x forbidden_arcanus:arcane_crystal_block",
                "3x #forge:ingots/silver",
            ],
            enchantment: "ensorcellation:quick_draw",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "ars_nouveau:source_gem_block",
                "2x forbidden_arcanus:arcane_crystal_block",
                "4x #forge:ingots/silver",
            ],
            enchantment: "ensorcellation:quick_draw",
            level: 4,
            sourceCost: 6500,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
                "5x #forge:ingots/silver",
            ],
            enchantment: "ensorcellation:quick_draw",
            level: 5,
            sourceCost: 9000,
        },
        {
            inputs: [
                "ars_nouveau:manipulation_essence",
                "2x ars_nouveau:source_gem_block",
                "iceandfire:ectoplasm",
            ],
            enchantment: "ensorcellation:magic_protection",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "2x ars_nouveau:manipulation_essence",
                "2x ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
                "2x iceandfire:ectoplasm",
            ],
            enchantment: "ensorcellation:magic_protection",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "3x ars_nouveau:manipulation_essence",
                "ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
                "3x iceandfire:ectoplasm",
            ],
            enchantment: "ensorcellation:magic_protection",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "2x ars_nouveau:manipulation_essence",
                "ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
                "4x iceandfire:ectoplasm",
            ],
            enchantment: "ensorcellation:magic_protection",
            level: 4,
            sourceCost: 6500,
        },
        {
            inputs: [
                "ars_nouveau:conjuration_essence",
                "ars_nouveau:source_gem_block",
                "forbidden_arcanus:xpetrified_orb",
            ],
            enchantment: "ensorcellation:xp_boost",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "2x ars_nouveau:conjuration_essence",
                "ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
                "2x forbidden_arcanus:xpetrified_orb",
            ],
            enchantment: "ensorcellation:xp_boost",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "2x ars_nouveau:conjuration_essence",
                "2x ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
                "3x forbidden_arcanus:xpetrified_orb",
            ],
            enchantment: "ensorcellation:xp_boost",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
                "ecologics:crab_claw",
            ],
            enchantment: "ensorcellation:reach",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "2x ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
                "2x ecologics:crab_claw",
            ],
            enchantment: "ensorcellation:reach",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "2x ars_nouveau:source_gem_block",
                "2x forbidden_arcanus:arcane_crystal_block",
                "2x ecologics:crab_claw",
            ],
            enchantment: "ensorcellation:reach",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_novueau:earth_essence",
                "ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
                "eidolon:zombie_heart",
            ],
            enchantment: "ensorcellation:vitality",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "2x ars_novueau:earth_essence",
                "2x ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
                "2x eidolon:zombie_heart",
            ],
            enchantment: "ensorcellation:vitality",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "3x ars_novueau:earth_essence",
                "2x ars_nouveau:source_gem_block",
                "3x eidolon:zombie_heart",
            ],
            enchantment: "ensorcellation:vitality",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_novueau:water_essence",
                "2x ars_nouveau:source_gem_block",
                "2x forbidden_arcanus:arcane_crystal_block",
                "neapolitan:ice_cubes",
            ],
            enchantment: "ensorcellation:frost_aspect",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "2x ars_novueau:water_essence",
                "2x ars_nouveau:source_gem_block",
                "2x forbidden_arcanus:arcane_crystal_block",
                "2x neapolitan:ice_cubes",
            ],
            enchantment: "ensorcellation:frost_aspect",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "graveyard:corruption",
                "2x ars_nouveau:source_gem_block",
                "2x forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "ensorcellation:leech",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "2x graveyard:corruption",
                "2x ars_nouveau:source_gem_block",
                "2x forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "ensorcellation:leech",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "3x graveyard:corruption",
                "2x ars_nouveau:source_gem_block",
                "2x forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "ensorcellation:leech",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "4x graveyard:corruption",
                "2x ars_nouveau:source_gem_block",
                "2x forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "ensorcellation:leech",
            level: 4,
            sourceCost: 6500,
        },
        {
            inputs: [
                "bosses_of_mass_destruction:soul_star",
                "ars_nouveau:air_essence",
                "2x ars_novueau:source_gem_block",
            ],
            enchantment: "ensorcellation:trueshot",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "2x bosses_of_mass_destruction:soul_star",
                "2x ars_nouveau:air_essence",
                "2x ars_novueau:source_gem_block",
            ],
            enchantment: "ensorcellation:trueshot",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "2x ars_novueau:conjuration_essence",
                "ars_nouveau:air_essence",
                "5x ars_novueau:source_gem_block",
            ],
            enchantment: "ensorcellation:volley",
            level: 1,
            sourceCost: 9000,
        },
        {
            inputs: [
                "2x alexsmobs:rocky_shell",
                "ars_nouveau:earth_essence",
                "5x ars_novueau:source_gem_block",
            ],
            enchantment: "ensorcellation:bulwark",
            level: 1,
            sourceCost: 9000,
        },
        {
            inputs: [
                "theurgy:sal_ammoniac_crystal",
                "ars_nouveau:water_essence",
                "2x ars_novueau:source_gem_block",
            ],
            enchantment: "ensorcellation:phalanx",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "2x theurgy:sal_ammoniac_crystal",
                "2x ars_nouveau:water_essence",
                "3x ars_novueau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "ensorcellation:phalanx",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "eidolon:wraith_heart",
                "eidolon:zombie_heart",
                "aquamirae:ship_graveyard_echo",
                "ars_nouveau:manipulation_essence",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "ensorcellation:soulbound",
            level: 1,
            sourceCost: 7500,
        },
        {
            inputs: [
                "ars_nouveau:fire_essence",
                "irons_spellbooks:blood_vial",
                "eidolon:death_essence",
                "2x ars_novueau:source_gem_block",
                "3x forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "majruszsenchantments:death_wish",
            level: 1,
            sourceCost: 9000,
        },
        {
            inputs: [
                "ars_nouveau:water_essence",
                "delightful:green_tea_leaf",
                "ars_novueau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "majruszsenchantments:dodge",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "2x ars_nouveau:water_essence",
                "2x delightful:green_tea_leaf",
                "2x ars_novueau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "majruszsenchantments:dodge",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "ars_nouveau:earth_essence",
                "reliquary:catalyzing_gland",
                "3x ars_novueau:source_gem_block",
                "3x forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "majruszsenchantments:fuse_cutter",
            level: 1,
            sourceCost: 9000,
        },
        {
            inputs: ["8x #forge:storage_blocks/gold"],
            enchantment: "majruszsenchantments:gold_fuelled",
            level: 1,
            sourceCost: 9000,
        },
        {
            inputs: [
                "ars_nouveau:abjuration_essence",
                "farmersdelight:tomato",
                "farmersdelight:rice",
                "minecraft:bread",
                "minecraft:carrot",
                "ars_novueau:source_gem_block",
            ],
            enchantment: "majruszsenchantments:harvester",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "ars_nouveau:abjuration_essence",
                "farmersdelight:cabbage",
                "minecraft:beetroot",
                "miners_delight:cave_carrot",
                "supplementaries:flax",
                "2x ars_novueau:source_gem_block",
            ],
            enchantment: "majruszsenchantments:harvester",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "ars_nouveau:abjuration_essence",
                "farmersdelight:onion",
                "neapolitan:strawberries",
                "delightful:salmonberries",
                "alexsmobs:banana",
                "ars_novueau:source_gem_block",
            ],
            enchantment: "majruszsenchantments:harvester",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:earth_essence",
                "minecraft:leather",
                "2x ars_novueau:source_gem_block",
            ],
            enchantment: "majruszsenchantments:horse_protection",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "2x ars_nouveau:earth_essence",
                "minecraft:leather",
                "3x ars_novueau:source_gem_block",
            ],
            enchantment: "majruszsenchantments:horse_protection",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "3x ars_nouveau:earth_essence",
                "minecraft:leather",
                "3x ars_novueau:source_gem_block",
            ],
            enchantment: "majruszsenchantments:horse_protection",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "3x ars_nouveau:earth_essence",
                "minecraft:leather",
                "4x ars_novueau:source_gem_block",
            ],
            enchantment: "majruszsenchantments:horse_protection",
            level: 4,
            sourceCost: 6500,
        },
        {
            inputs: [
                "2x ars_nouveau:manipulation_essence",
                "iceandfire:pixie_wings",
                "3x ars_novueau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "majruszsenchantments:immortality",
            level: 1,
            sourceCost: 9000,
        },
        {
            inputs: [
                "ars_nouveau:water_essence",
                "miners_delight:cave_carrot",
                "ars_novueau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "majruszsenchantments:horse_swiftness",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "ars_nouveau:water_essence",
                "2x miners_delight:cave_carrot",
                "ars_novueau:source_gem_block",
                "2x forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "majruszsenchantments:horse_swiftness",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "ars_nouveau:water_essence",
                "2x miners_delight:cave_carrot",
                "2x ars_novueau:source_gem_block",
                "2x forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "majruszsenchantments:horse_swiftness",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:water_essence",
                "2x miners_delight:cave_carrot",
                "2x ars_novueau:source_gem_block",
                "3x forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "majruszsenchantments:horse_swiftness",
            level: 4,
            sourceCost: 6500,
        },
        {
            inputs: [
                "ars_nouveau:abjuration_essence",
                "ars_nouveau:manipulation_essence",
                "minecraft:emerald",
                "ars_novueau:source_gem_block",
            ],
            enchantment: "majruszsenchantments:misanthropy",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "2x ars_nouveau:abjuration_essence",
                "ars_nouveau:manipulation_essence",
                "minecraft:emerald",
                "2x ars_novueau:source_gem_block",
            ],
            enchantment: "majruszsenchantments:misanthropy",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "2x ars_nouveau:abjuration_essence",
                "2x ars_nouveau:manipulation_essence",
                "minecraft:emerald_block",
                "3x ars_novueau:source_gem_block",
            ],
            enchantment: "majruszsenchantments:misanthropy",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:abjuration_essence",
                "2x ars_nouveau:manipulation_essence",
                "minecraft:emerald_block",
                "4x ars_novueau:source_gem_block",
            ],
            enchantment: "majruszsenchantments:misanthropy",
            level: 4,
            sourceCost: 6500,
        },
        {
            inputs: [
                "ars_nouveau:abjuration_essence",
                "ars_nouveau:manipulation_essence",
                "minecraft:emerald_block",
                "5x ars_novueau:source_gem_block",
            ],
            enchantment: "majruszsenchantments:misanthropy",
            level: 5,
            sourceCost: 9000,
        },
        {
            inputs: [
                "ars_nouveau:fire_essence",
                "ars_nouveau:manipulation_essence",
                "minecraft:furnace",
                "3x ars_novueau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_dust",
            ],
            enchantment: "majruszsenchantments:smelter",
            level: 1,
            sourceCost: 9000,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "2x ars_nouveau:manipulation_essence",
                "endermanoverhaul:summoner_pearl",
                "4x ars_novueau:source_gem_block",
            ],
            enchantment: "majruszsenchantments:telekinesis",
            level: 1,
            sourceCost: 9000,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "thermal:cinnabar_block",
                "forbidden_arcanus:arcane_crystal_block",
                "ars_novueau:source_gem_block",
            ],
            enchantment: "enigmaticlegacy:sharpshooter",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "2x thermal:cinnabar_block",
                "forbidden_arcanus:arcane_crystal_block",
                "2x ars_novueau:source_gem_block",
            ],
            enchantment: "enigmaticlegacy:sharpshooter",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "3x thermal:cinnabar_block",
                "forbidden_arcanus:arcane_crystal_block",
                "2x ars_novueau:source_gem_block",
            ],
            enchantment: "enigmaticlegacy:sharpshooter",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "3x thermal:cinnabar_block",
                "forbidden_arcanus:arcane_crystal_block",
                "3x ars_novueau:source_gem_block",
            ],
            enchantment: "enigmaticlegacy:sharpshooter",
            level: 4,
            sourceCost: 6500,
        },
        {
            inputs: ["7x ars_nouveau:air_essence", "eidolon:wraith_heart"],
            enchantment: "enigmaticlegacy:ceaseless",
            level: 1,
            sourceCost: 9000,
        },
        {
            inputs: ["2x ars_nouveau:water_essence", "#minecraft:corals"],
            enchantment: "enigmaticlegacy:torrent",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: ["3x ars_nouveau:water_essence", "2x #minecraft:corals"],
            enchantment: "enigmaticlegacy:torrent",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: ["4x ars_nouveau:water_essence", "2x #minecraft:corals"],
            enchantment: "enigmaticlegacy:torrent",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "4x ars_nouveau:water_essence",
                "2x #minecraft:corals",
                "aquamirae:fin",
            ],
            enchantment: "enigmaticlegacy:torrent",
            level: 4,
            sourceCost: 6500,
        },
        {
            inputs: [
                "5x ars_nouveau:water_essence",
                "#minecraft:corals",
                "aquamirae:fin",
                "alexsmobs:fish_bones",
            ],
            enchantment: "enigmaticlegacy:torrent",
            level: 5,
            sourceCost: 9000,
        },
        {
            inputs: [
                "2x ars_nouveau:water_essence",
                "forbidden_arcanus:arcane_crystal_block",
                "theurgy:sal_ammoniac_crystal",
            ],
            enchantment: "enigmaticlegacy:wrath",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "3x ars_nouveau:water_essence",
                "2x forbidden_arcanus:arcane_crystal_block",
                "theurgy:sal_ammoniac_crystal",
            ],
            enchantment: "enigmaticlegacy:wrath",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "3x ars_nouveau:water_essence",
                "2x forbidden_arcanus:arcane_crystal_block",
                "2x theurgy:sal_ammoniac_crystal",
            ],
            enchantment: "enigmaticlegacy:wrath",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "4x ars_nouveau:water_essence",
                "2x forbidden_arcanus:arcane_crystal_block",
                "2x theurgy:sal_ammoniac_crystal",
            ],
            enchantment: "enigmaticlegacy:wrath",
            level: 4,
            sourceCost: 6500,
        },
        {
            inputs: [
                "3x ars_nouveau:water_essence",
                "2x forbidden_arcanus:arcane_crystal_block",
                "3x theurgy:sal_ammoniac_crystal",
            ],
            enchantment: "enigmaticlegacy:wrath",
            level: 5,
            sourceCost: 9000,
        },
        {
            inputs: [
                "ars_nouveau:abjuration_essence",
                "ars_nouveau:source_gem_block",
                "eidolon:tattered_cloth",
                "minecraft:rotten_flesh",
            ],
            enchantment: "enigmaticlegacy:slayer",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "ars_nouveau:abjuration_essence",
                "ars_nouveau:source_gem_block",
                "eidolon:tattered_cloth",
                "2x minecraft:rotten_flesh",
            ],
            enchantment: "enigmaticlegacy:slayer",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "ars_nouveau:abjuration_essence",
                "2x ars_nouveau:source_gem_block",
                "2x eidolon:tattered_cloth",
                "minecraft:bone",
            ],
            enchantment: "enigmaticlegacy:slayer",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "2x ars_nouveau:abjuration_essence",
                "2x ars_nouveau:source_gem_block",
                "minecraft:spider_eye",
                "2x iceandfire:ectoplasm",
            ],
            enchantment: "enigmaticlegacy:slayer",
            level: 4,
            sourceCost: 6500,
        },
        {
            inputs: [
                "2x ars_nouveau:abjuration_essence",
                "3x ars_nouveau:source_gem_block",
                "3x iceandfire:ectoplasm",
            ],
            enchantment: "enigmaticlegacy:slayer",
            level: 5,
            sourceCost: 9000,
        },
        {
            inputs: [
                "ars_nouveau:abjuration_essence",
                "ars_nouveau:manipulation_essence",
                "ars_nouveau:source_gem_block",
                "alexscaves:guano",
            ],
            enchantment: "apotheosis:berserkers_fury",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "2x ars_nouveau:abjuration_essence",
                "ars_nouveau:manipulation_essence",
                "2x ars_nouveau:source_gem_block",
                "2x alexscaves:guano",
            ],
            enchantment: "apotheosis:berserkers_fury",
            level: 2,
            sourceCost: 7500,
        },
        {
            inputs: [
                "3x ars_nouveau:manipulation_essence",
                "2x ars_nouveau:source_gem_block",
                "alexscaves:tree_star",
                "#forge:crops/cabbage",
                "delightful:green_tea_leaf",
            ],
            enchantment: "apotheosis:chainsaw",
            level: 1,
            sourceCost: 15000,
        },
        {
            inputs: [
                "4x ars_nouveau:manipulation_essence",
                "ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
                "2x alexsmobs:rainbow_jelly",
            ],
            enchantment: "apotheosis:chromatic",
            level: 1,
            sourceCost: 9000,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "2x mowziesmobs:dart",
                "irons_spellbooks:arcane_ingot",
                "irons_spellbooks:frozen_bone",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "apotheosis:crescendo",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "2x ars_nouveau:air_essence",
                "3x mowziesmobs:dart",
                "irons_spellbooks:arcane_ingot",
                "irons_spellbooks:frozen_bone",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "apotheosis:crescendo",
            level: 2,
            sourceCost: 7500,
        },
        {
            inputs: [
                "#forge:storage_blocks/nickel",
                "#forge:storage_blocks/silver",
                "#forge:storage_blocks/iron",
                "#forge:storage_blocks/aluminum",
            ],
            enchantment: "apotheosis:earths_boon",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "#forge:storage_blocks/nickel",
                "#forge:storage_blocks/silver",
                "#forge:storage_blocks/iron",
                "#forge:storage_blocks/aluminum",
                "#forge:storage_blocks/gold",
                "#forge:storage_blocks/tin",
                "#forge:storage_blocks/lead",
                "#forge:storage_blocks/copper",
            ],
            enchantment: "apotheosis:earths_boon",
            level: 2,
            sourceCost: 7500,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "alexsmobs:skreecher_soul",
                "aether_redux:gravitite_ingot",
                "conjurer_illager:throwing_card",
                "ars_nouveau:source_gem_block",
            ],
            enchantment: "apotheosis:endless_quiver",
            level: 1,
            sourceCost: 15000,
        },
        {
            inputs: [
                "2x eidolon:death_essence",
                "forbidden_arcanus:dark_rune",
                "3x forbidden_arcanus:arcane_crystal_block",
                "2x ars_nouveau:source_gem_block",
            ],
            enchantment: "apotheosis:exploitation",
            level: 1,
            sourceCost: 15000,
        },
        {
            inputs: [
                "2x irons_spellbooks:divine_pearl",
                "forbidden_arcanus:rune",
                "forbidden_arcanus:arcane_crystal_block",
                "2x ars_nouveau:source_gem_block",
            ],
            enchantment: "apotheosis:growth_serum",
            level: 1,
            sourceCost: 15000,
        },
        {
            inputs: [
                "ars_nouveau:water_essence",
                "irons_spellbooks:frozen_bone",
                "2x upgrade_aquatic:thrasher_tooth",
                "forbidden_arcanus:arcane_crystal_block",
                "2x ars_nouveau:source_gem_block",
            ],
            enchantment: "apotheosis:icy_thorns",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "2x ars_nouveau:water_essence",
                "2x irons_spellbooks:frozen_bone",
                "2x upgrade_aquatic:thrasher_tooth",
                "forbidden_arcanus:arcane_crystal_block",
                "ars_nouveau:source_gem_block",
            ],
            enchantment: "apotheosis:icy_thorns",
            level: 2,
            sourceCost: 7500,
        },
        {
            inputs: [
                "2x forbidden_arcanus:xpetrified_orb",
                "2x ars_nouveau:experience_gem",
            ],
            enchantment: "apotheosis:knowledge",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "4x forbidden_arcanus:xpetrified_orb",
                "4x ars_nouveau:experience_gem",
            ],
            enchantment: "apotheosis:knowledge",
            level: 2,
            sourceCost: 7500,
        },
        {
            inputs: [
                "ars_nouveau:earth_essence",
                "4x #forge:storage_blocks/diamond",
            ],
            enchantment: "apotheosis:miners_fervor",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:earth_essence",
                "5x #forge:storage_blocks/diamond",
            ],
            enchantment: "apotheosis:miners_fervor",
            level: 2,
            sourceCost: 7500,
        },
        {
            inputs: [
                "ars_nouveau:earth_essence",
                "berry_good:glow_berry_pips",
                "delightful:cantaloupe_seeds",
                "2x #forge:seeds",
                "forbidden_arcanus:arcane_crystal_block",
                "2x ars_nouveau:source_gem_block",
            ],
            enchantment: "apotheosis:natures_blessing",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:earth_essence",
                "farmersdelight:potato_seeds",
                "neapolitan:strawberry_pips",
                "occultism:datura_seeds",
                "#forge:seeds",
                "forbidden_arcanus:arcane_crystal_block",
                "2x ars_nouveau:source_gem_block",
            ],
            enchantment: "apotheosis:natures_blessing",
            level: 2,
            sourceCost: 7500,
        },
        {
            inputs: [
                "3x ars_nouveau:earth_essence",
                "2x forbidden_arcanus:arcane_crystal_block",
                "3x ars_nouveau:source_gem_block",
            ],
            enchantment: "apotheosis:natures_blessing",
            level: 3,
            sourceCost: 10000,
        },
        {
            inputs: [
                "ars_nouveau:manipulation_essence",
                "2x forbidden_arcanus:arcane_crystal_block",
                "2x ars_nouveau:source_gem_block",
                "2x apotheosis:common_material",
            ],
            enchantment: "apotheosis:obliteration",
            level: 1,
            sourceCost: 9000,
        },
        {
            inputs: [
                "ars_nouveau:abjuration_essence",
                "2x forbidden_arcanus:arcane_crystal_block",
                "supplementaries:spring_launcher",
                "immersiveengineering:hemp_fabric",
            ],
            enchantment: "apotheosis:rebounding",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "2x ars_nouveau:abjuration_essence",
                "2x forbidden_arcanus:arcane_crystal_block",
                "supplementaries:spring_launcher",
                "2x immersiveengineering:hemp_fabric",
            ],
            enchantment: "apotheosis:rebounding",
            level: 2,
            sourceCost: 7500,
        },
        {
            inputs: [
                "3x ars_nouveau:abjuration_essence",
                "2x forbidden_arcanus:arcane_crystal_block",
                "3x immersiveengineering:hemp_fabric",
            ],
            enchantment: "apotheosis:rebounding",
            level: 3,
            sourceCost: 10000,
        },
        {
            inputs: [
                "botania:livingrock",
                "caverns_and_chasms:spinel",
                "ars_nouveau:source_gem_block",
                "delightful:cantaloupe_slice",
            ],
            enchantment: "apotheosis:reflective",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "botania:livingrock",
                "2x caverns_and_chasms:spinel",
                "2x ars_nouveau:source_gem_block",
                "delightful:cantaloupe_slice",
            ],
            enchantment: "apotheosis:reflective",
            level: 2,
            sourceCost: 7500,
        },
        {
            inputs: [
                "3x botania:livingrock",
                "2x caverns_and_chasms:spinel",
                "2x ars_nouveau:source_gem_block",
                "delightful:cantaloupe_slice",
            ],
            enchantment: "apotheosis:reflective",
            level: 3,
            sourceCost: 10000,
        },
        {
            inputs: [
                "ars_nouveau:earth_essence",
                "2x alexscaves:sea_glass_shards",
                "5x ars_nouveau:source_gem_block",
            ],
            enchantment: "apotheosis:scavenger",
            level: 1,
            sourceCost: 10000,
        },
        {
            inputs: [
                "3x alexscaves:sea_glass_shards",
                "5x ars_nouveau:source_gem_block",
            ],
            enchantment: "apotheosis:scavenger",
            level: 2,
            sourceCost: 15000,
        },
        {
            inputs: [
                "ars_nouveau:earth_essence",
                "2x immersiveengineering:hemp_fabric",
                "ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "apotheosis:shield_bash",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:earth_essence",
                "2x immersiveengineering:hemp_fabric",
                "2x ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "apotheosis:shield_bash",
            level: 2,
            sourceCost: 7500,
        },
        {
            inputs: [
                "ars_nouveau:earth_essence",
                "2x immersiveengineering:hemp_fabric",
                "3x ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "apotheosis:shield_bash",
            level: 3,
            sourceCost: 10000,
        },
        {
            inputs: [
                "ars_nouveau:earth_essence",
                "2x immersiveengineering:hemp_fabric",
                "4x ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "apotheosis:shield_bash",
            level: 4,
            sourceCost: 12500,
        },
        {
            inputs: ["ars_nouveau:water_essence", "7x #minecraft:fishes"],
            enchantment: "apotheosis:spearfishing",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:water_essence",
                "6x #minecraft:fishes",
                "miners_delight:squid",
            ],
            enchantment: "apotheosis:spearfishing",
            level: 2,
            sourceCost: 7500,
        },
        {
            inputs: [
                "ars_nouveau:water_essence",
                "5x #minecraft:fishes",
                "cataclysm:lionfish",
                "alexsmobs:blobfish",
            ],
            enchantment: "apotheosis:spearfishing",
            level: 3,
            sourceCost: 10000,
        },
        // {
        //     inputs: [
        //         "ars_nouveau:water_essence",
        //         "5x #minecraft:fishes",
        //         "upgrade_aquatic:lionfish",
        //         "alexsmobs:blobfish",
        //     ],
        //     enchantment: "apotheosis:spearfishing",
        //     level: 3,
        //     sourceCost: 10000,
        // },
        {
            inputs: [
                "ars_nouveau:water_essence",
                "5x #minecraft:fishes",
                "aquamirae:spinefish",
                "alexscaves:lanternfish",
            ],
            enchantment: "apotheosis:spearfishing",
            level: 4,
            sourceCost: 12500,
        },
        {
            inputs: [
                "2x ars_nouveau:manipulation_essence",
                "2x ars_nouveau:source_gem_block",
                "2x forbidden_arcanus:arcane_crystal_block",
                "apotheosis:uncommon_material",
            ],
            enchantment: "apotheosis:splitting",
            level: 1,
            sourceCost: 9000,
        },
        {
            inputs: [
                "ars_nouveau:manipulation_essence",
                "ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
                "minecraft:wheat",
                "minecraft:wheat_seeds",
                "minecraft:carrot",
            ],
            enchantment: "apotheosis:tempting",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "forbidden_arcanus:rune",
                "3x ars_nouveau:source_gem_block",
                "4x paraglider:spirit_orb",
            ],
            enchantment: "apotheosis:capturing",
            level: 1,
            sourceCost: 5000,
        },
        {
            inputs: [
                "forbidden_arcanus:rune",
                "2x ars_nouveau:source_gem_block",
                "5x paraglider:spirit_orb",
            ],
            enchantment: "apotheosis:capturing",
            level: 2,
            sourceCost: 7500,
        },
        {
            inputs: [
                "2x forbidden_arcanus:rune",
                "ars_nouveau:source_gem_block",
                "5x paraglider:spirit_orb",
            ],
            enchantment: "apotheosis:capturing",
            level: 3,
            sourceCost: 10000,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "forbidden_arcanus:arcane_crystal_block",
                "2x paraglider:spirit_orb",
                "2x farmersdelight:apple_pie_slice",
            ],
            enchantment: "feathers:lightweight",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "forbidden_arcanus:arcane_crystal_block",
                "3x paraglider:spirit_orb",
                "3x farmersdelight:apple_pie_slice",
            ],
            enchantment: "feathers:lightweight",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "2x forbidden_arcanus:arcane_crystal_block",
                "3x paraglider:spirit_orb",
                "2x farmersdelight:apple_pie_slice",
            ],
            enchantment: "feathers:lightweight",
            level: 3,
            sourceCost: 6000,
        },
        // {
        //     inputs: [
        //         "forbidden_arcanus:xpetrified_orb",
        //         "ars_nouveau:experience_gem",
        //         "create:experience_block",
        //         "actuallyadditions:solidified_experience",
        //     ],
        //     enchantment: "allurement:alleviating",
        //     level: 1,
        //     sourceCost: 9000,
        // },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "paraglider:paraglider",
                "aquamirae:esca",
                "ars_nouveau:source_gem_block",
            ],
            enchantment: "allurement:launch",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "paraglider:paraglider",
                "iceandfire:pixie_dust",
                "ars_nouveau:source_gem_block",
            ],
            enchantment: "allurement:launch",
            level: 2,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "minecraft:fishing_rod",
                "aquaculture:diamond_hook",
                "ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "allurement:reeling",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "ars_nouveau:air_essence",
                "minecraft:fishing_rod",
                "aquaculture:neptunium_ingot",
                "ars_nouveau:source_gem_block",
            ],
            enchantment: "allurement:reeling",
            level: 2,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:earth_essence",
                "ars_nouveau:abjuration_essence",
                "thermal:blitz_powder",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "allurement:shockwave",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "2x ars_nouveau:earth_essence",
                "ars_nouveau:abjuration_essence",
                "2x thermal:blitz_powder",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "allurement:shockwave",
            level: 2,
            sourceCost: 3500,
        },
        {
            inputs: [
                "2x ars_nouveau:earth_essence",
                "2x ars_nouveau:abjuration_essence",
                "2x thermal:blitz_powder",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "allurement:shockwave",
            level: 3,
            sourceCost: 5000,
        },
        {
            inputs: [
                "3x ars_nouveau:earth_essence",
                "2x ars_nouveau:abjuration_essence",
                "2x thermal:blitz_powder",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "allurement:shockwave",
            level: 4,
            sourceCost: 6500,
        },
        {
            inputs: [
                "ars_nouveau:conjuration_essence",
                "4x irons_spellbooks:blood_vial",
                "ars_nouveau:source_gem_block",
            ],
            enchantment: "allurement:spread_of_ailments",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "ars_nouveau:conjuration_essence",
                "5x irons_spellbooks:blood_vial",
                "ars_nouveau:source_gem_block",
                "forbidden_arcanus:arcane_crystal_block",
            ],
            enchantment: "allurement:spread_of_ailments",
            level: 2,
            sourceCost: 5000,
        },
        {
            inputs: [
                "ars_nouveau:abjuration_essence",
                "ars_nouveau:fire_essence",
                "2x irons_spellbooks:blood_vial",
                "forbidden_arcanus:dark_matter",
                "ars_nouveau:source_gem_block",
            ],
            enchantment: "allurement:vengeance",
            level: 1,
            sourceCost: 2000,
        },
        {
            inputs: [
                "ars_nouveau:abjuration_essence",
                "2x ars_nouveau:fire_essence",
                "irons_spellbooks:blood_vial",
                "forbidden_arcanus:dark_matter",
                "ars_nouveau:source_gem_block",
            ],
            enchantment: "allurement:vengeance",
            level: 2,
            sourceCost: 5000,
        },
        {
            inputs: [
                "4x iceandfire:wither_shard",
                "4x ars_nouveau:source_gem_block",
            ],
            enchantment: "enderio:withering",
            level: 1,
            sourceCost: 9000,
        },
    ];

    recipes.forEach((recipe) => {
        // These exist so I can be lazy
        const sourceCost = recipe.sourceCost ? recipe.SourceCost : 2000;
        const keepNBT = recipe.keepNBT ? recipe.keepNBT : true;

        event.recipes.ars_nouveau.enchantment(
            recipe.inputs,
            recipe.enchantment,
            recipe.level,
            recipe.sourceCost
        );
    });
});
