name: "Bug Report"
description: "Report a glitch, bug, or unexpected behavior."
labels:
    - Bug

body:
    - type: markdown
      id: start
      attributes:
          value: "Thank you for helping by reporting bugs. Please fill out the fields below to give me all the information I'll need to investigate."

    - type: input
      id: title
      attributes:
          label: "Description"
          description: "Provide a short and clear description of the issue."
      validations:
          required: true

    - type: textarea
      id: steps_to_reproduce
      attributes:
          label: "Steps to Reproduce"
          description: "Clearly describe how to reproduce the issue. Assume you're in creative mode unless the bug requires being in survival. If the bug is straightforward, you can leave this field blank."
          placeholder: "
              1.
              2. ..."
      validations:
          required: false

    - type: textarea
      id: related_mods
      attributes:
          label: "Involved Mods"
          description: "What mods are involved? If you don't know what to put here, write 'Unknown'."
          placeholder: "
              -
              - ..."
      validations:
          required: true

    - type: textarea
      id: related_mods
      attributes:
          label: "Upload a Log"
          description: "Please upload your latest.log or log containing the issue. Use a website like [GitHub Gist](https://gist.github.com/) or [mclo.gs](https://mclo.gs) to upload the log."
      validations:
          required: false

    - type: textarea
      id: additional_context
      attributes:
          label: "Additional Context"
          description: "Add any other context about the problem here. Do you have screenshots? Did you add any mods?"
      validations:
          required: false
