
["Mob Spawning"]
	#Defines the biomes that Chameleons can spawn in
	#Format: [["biome_id", weight], ["biome_id", weight], etc...]
	"Chameleon Spawn Biomes" = [["minecraft:bamboo_jungle", 80], ["minecraft:jungle", 80], ["minecraft:sparse_jungle", 35], ["minecraft:desert", 1]]
	#Defines additional biomes that goats can spawn in
	#Format: [["biome_id", weight], ["biome_id", weight], etc...]
	#Not affected by the "Increase Goat Spawns" option
	"Goat Spawn Biomes" = [["minecraft:frozen_peaks", 8], ["minecraft:jagged_peaks", 8], ["minecraft:snowy_slopes", 8], ["minecraft:meadow", 3], ["minecraft:windswept_hills", 6], ["minecraft:windswept_forest", 6], ["minecraft:windswept_gravelly_hills", 4], ["minecraft:grove", 5], ["minecraft:stony_peaks", 8]]

["Entity Temperature"]
	#List of entities that will insulate the player when riding them
	#A value of 0 provides no insulation; 1 provides full insulation
	#Format: [["entity_id", coldResistance, hotResistance], ["entity_id", coldResistance, hotResistance], etc...]
	"Insulated Mounts" = []
	#Defines temperature-emitting properties for entities
	#Format: [["entity_id", temperature, range, *units], ["entity_id", temperature, range, *units], etc...]
	#temperature: The temperature emitted by the entity
	#range: The range of the effect, in blocks
	#units: (Optional) The units of the temperature value (MC, F, or C). Defaults to MC
	"Entity Temperatures" = [["cataclysm:ignis", 0.5, 12], ["cataclysm:netherite_monstrosity", 0.4, 12], ["mowziesmobs:frostmaw", -0.4, 8], ["mowziesmobs:umvuthi", 0.55, 4], ["eidolon:wraith", -0.1, 3], ["iceandfire:fire_dragon", 0.2, 5], ["iceandfire:ice_dragon", -0.2, 5], ["thermal:blizz", -0.15, 6], ["thermal:blitz", 0.15, 6], ["minecraft:blaze", 0.13, 6], ["alexsmobs:froststalker", -0.08, 3], ["alexsmobs:guster", -0.1, 7]]

["Fur Growth & Shedding"]
	#Defines how often a goat will try to grow its fur, the growth cooldown after shearing, and the chance of it succeeding
	#Format: [interval, cooldown, chance]
	"Goat Fur Growth Timings" = [1200, 2400, 0.2]
	#Defines how often a chameleon will try to shed its skin, the cooldown after shedding, and the chance of it succeeding
	#Format: [interval, cooldown, chance]
	"Chameleon Shedding Timings" = [100, 36000, 0.1]

