#List of curio slot type settings
# keepCurios = "ON"
# [[curiosSettings]]
#   identifier = "ring"
#   size = 2
#   override = true
[[curiosSettings]]
identifier = "head"
size = 1
override = true
[[curiosSettings]]
identifier = "necklace"
size = 1
override = true
# [[curiosSettings]]
# identifier = "head"
# size = 1
# override = true
[[curiosSettings]]
identifier = "ring"
size = 1
override = true
[[curiosSettings]]
identifier = "belt"
size = 1
override = true
[[curiosSettings]]
identifier = "charm"
size = 1
override = true
[[curiosSettings]]
identifier = "bracelet"
size = 1
override = true
[[curiosSettings]]
identifier = "hands"
size = 0
override = true
[[curiosSettings]]
identifier = "back"
size = 2
override = true
