[Misc]
rarityConfig = [ 0.3, 0.25, 0.2, 0.15, 0.1,]
swordsConsumeMana = true
swordsCooldownMultiplier = 0.5
canAttackOwnSummons = false
maxUpgrades = 3
manaSpawnPercent = 0.75
runWorldUpgrader = true
scrollRecycleChance = 0.5
allowCauldronBrewing = true

["Upgrade Overrides"]
upgradeWhitelist = []
upgradeBlacklist = []

["Imbue Overrides"]
imbueWhitelist = []
imbueBlacklist = []

[Worldgen]
priestHouseWeight = 4

[Spells."irons_spellbooks:fireball"]
Enabled = true
School = "irons_spellbooks:fire"
MaxLevel = 3
MinRarity = "EPIC"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 5.6

[Spells."irons_spellbooks:wall_of_fire"]
Enabled = true
School = "irons_spellbooks:fire"
MaxLevel = 5
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 4.5

[Spells."irons_spellbooks:fire_breath"]
Enabled = true
School = "irons_spellbooks:fire"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.7

[Spells."irons_spellbooks:magma_bomb"]
Enabled = true
School = "irons_spellbooks:fire"
MaxLevel = 8
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.2

[Spells."irons_spellbooks:burning_dash"]
Enabled = true
School = "irons_spellbooks:fire"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 2.7

[Spells."irons_spellbooks:blaze_storm"]
Enabled = true
School = "irons_spellbooks:fire"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 5.3

[Spells."irons_spellbooks:firebolt"]
Enabled = true
School = "irons_spellbooks:fire"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 0.5

[Spells."irons_spellbooks:poison_arrow"]
Enabled = true
School = "irons_spellbooks:nature"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.9

[Spells."irons_spellbooks:earthquake"]
Enabled = true
School = "irons_spellbooks:nature"
MaxLevel = 10
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.7

[Spells."irons_spellbooks:poison_splash"]
Enabled = true
School = "irons_spellbooks:nature"
MaxLevel = 10
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 4.9

[Spells."irons_spellbooks:oakskin"]
Enabled = true
School = "irons_spellbooks:nature"
MaxLevel = 8
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 7.3

[Spells."irons_spellbooks:spider_aspect"]
Enabled = true
School = "irons_spellbooks:nature"
MaxLevel = 8
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 60.0

[Spells."irons_spellbooks:firefly_swarm"]
Enabled = true
School = "irons_spellbooks:nature"
MaxLevel = 10
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 5.4

[Spells."irons_spellbooks:root"]
Enabled = true
School = "irons_spellbooks:nature"
MaxLevel = 10
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 7.0

[Spells."irons_spellbooks:blight"]
Enabled = true
School = "irons_spellbooks:nature"
MaxLevel = 8
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 6.7

[Spells."irons_spellbooks:acid_orb"]
Enabled = true
School = "irons_spellbooks:nature"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 4.0

[Spells."irons_spellbooks:poison_breath"]
Enabled = true
School = "irons_spellbooks:nature"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.1

[Spells."irons_spellbooks:fang_ward"]
Enabled = true
School = "irons_spellbooks:evocation"
MaxLevel = 8
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.6

[Spells."irons_spellbooks:fang_strike"]
Enabled = true
School = "irons_spellbooks:evocation"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 2.0

[Spells."irons_spellbooks:chain_creeper"]
Enabled = true
School = "irons_spellbooks:evocation"
MaxLevel = 6
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.7

[Spells."irons_spellbooks:gust"]
Enabled = true
School = "irons_spellbooks:evocation"
MaxLevel = 10
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.4

[Spells."irons_spellbooks:invisibility"]
Enabled = true
School = "irons_spellbooks:evocation"
MaxLevel = 6
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 9.8

[Spells."irons_spellbooks:summon_vex"]
Enabled = true
School = "irons_spellbooks:evocation"
MaxLevel = 5
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 26.0

[Spells."irons_spellbooks:lob_creeper"]
Enabled = true
School = "irons_spellbooks:evocation"
MaxLevel = 10
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 0.9

[Spells."irons_spellbooks:shield"]
Enabled = true
School = "irons_spellbooks:evocation"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 2.2

[Spells."irons_spellbooks:summon_horse"]
Enabled = true
School = "irons_spellbooks:evocation"
MaxLevel = 5
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 5.3

[Spells."irons_spellbooks:spectral_hammer"]
Enabled = true
School = "irons_spellbooks:evocation"
MaxLevel = 5
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 2.8

[Spells."irons_spellbooks:firecracker"]
Enabled = true
School = "irons_spellbooks:evocation"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 0.7

[Spells."irons_spellbooks:frostbite"]
Enabled = false
School = "irons_spellbooks:ice"
MaxLevel = 0
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 0.5

[Spells."irons_spellbooks:ice_block"]
Enabled = true
School = "irons_spellbooks:ice"
MaxLevel = 6
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 4.0

[Spells."irons_spellbooks:ray_of_frost"]
Enabled = true
School = "irons_spellbooks:ice"
MaxLevel = 5
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.5

[Spells."irons_spellbooks:cone_of_cold"]
Enabled = true
School = "irons_spellbooks:ice"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.1

[Spells."irons_spellbooks:frost_step"]
Enabled = true
School = "irons_spellbooks:ice"
MaxLevel = 8
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.0

[Spells."irons_spellbooks:summon_polar_bear"]
Enabled = true
School = "irons_spellbooks:ice"
MaxLevel = 10
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 29.3

[Spells."irons_spellbooks:icicle"]
Enabled = true
School = "irons_spellbooks:ice"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 0.5

[Spells."irons_spellbooks:abyssal_shroud"]
Enabled = false
School = "irons_spellbooks:ender"
MaxLevel = 3
MinRarity = "LEGENDARY"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 40.4

[Spells."irons_spellbooks:evasion"]
Enabled = true
School = "irons_spellbooks:ender"
MaxLevel = 5
MinRarity = "EPIC"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 27.7

[Spells."irons_spellbooks:magic_missile"]
Enabled = true
School = "irons_spellbooks:ender"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 0.5

[Spells."irons_spellbooks:void_tentacles"]
Enabled = true
School = "irons_spellbooks:ender"
MaxLevel = 3
MinRarity = "LEGENDARY"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 7.4

[Spells."irons_spellbooks:summon_ender_chest"]
Enabled = true
School = "irons_spellbooks:ender"
MaxLevel = 1
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 1.8

[Spells."irons_spellbooks:magic_arrow"]
Enabled = true
School = "irons_spellbooks:ender"
MaxLevel = 10
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 2.8

[Spells."irons_spellbooks:teleport"]
Enabled = true
School = "irons_spellbooks:ender"
MaxLevel = 5
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 1.3

[Spells."irons_spellbooks:dragon_breath"]
Enabled = true
School = "irons_spellbooks:ender"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.8

[Spells."irons_spellbooks:black_hole"]
Enabled = true
School = "irons_spellbooks:ender"
MaxLevel = 6
MinRarity = "LEGENDARY"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 20.3

[Spells."irons_spellbooks:counterspell"]
Enabled = true
School = "irons_spellbooks:ender"
MaxLevel = 1
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.6

[Spells."irons_spellbooks:starfall"]
Enabled = true
School = "irons_spellbooks:ender"
MaxLevel = 10
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 4.3

[Spells."irons_spellbooks:healing_circle"]
Enabled = true
School = "irons_spellbooks:holy"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 0.6
CooldownInSeconds = 15.0

[Spells."irons_spellbooks:blessing_of_life"]
Enabled = true
School = "irons_spellbooks:holy"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 10.0

[Spells."irons_spellbooks:angel_wing"]
Enabled = true
School = "irons_spellbooks:holy"
MaxLevel = 5
MinRarity = "EPIC"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 120.0

[Spells."irons_spellbooks:sunbeam"]
Enabled = false
School = "irons_spellbooks:holy"
MaxLevel = 10
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 4.3

[Spells."irons_spellbooks:fortify"]
Enabled = true
School = "irons_spellbooks:holy"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 8.7

[Spells."irons_spellbooks:guiding_bolt"]
Enabled = true
School = "irons_spellbooks:holy"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 2.5

[Spells."irons_spellbooks:heal"]
Enabled = true
School = "irons_spellbooks:holy"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 0.6
CooldownInSeconds = 15.0

[Spells."irons_spellbooks:wisp"]
Enabled = true
School = "irons_spellbooks:holy"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 1.4

[Spells."irons_spellbooks:greater_heal"]
Enabled = true
School = "irons_spellbooks:holy"
MaxLevel = 1
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 0.6
CooldownInSeconds = 20.0

[Spells."irons_spellbooks:cloud_of_regeneration"]
Enabled = false
School = "irons_spellbooks:holy"
MaxLevel = 5
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 8.3

[Spells."irons_spellbooks:raise_dead"]
Enabled = true
School = "irons_spellbooks:blood"
MaxLevel = 6
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 90.0

[Spells."irons_spellbooks:blood_slash"]
Enabled = true
School = "irons_spellbooks:blood"
MaxLevel = 5
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.1

[Spells."irons_spellbooks:blood_step"]
Enabled = true
School = "irons_spellbooks:blood"
MaxLevel = 5
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 1.7

[Spells."irons_spellbooks:acupuncture"]
Enabled = true
School = "irons_spellbooks:blood"
MaxLevel = 10
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 4.7

[Spells."irons_spellbooks:ray_of_siphoning"]
Enabled = true
School = "irons_spellbooks:blood"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 4.6

[Spells."irons_spellbooks:blood_needles"]
Enabled = true
School = "irons_spellbooks:blood"
MaxLevel = 10
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 2.6

[Spells."irons_spellbooks:heartstop"]
Enabled = true
School = "irons_spellbooks:blood"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 19.3

[Spells."irons_spellbooks:devour"]
Enabled = true
School = "irons_spellbooks:blood"
MaxLevel = 10
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 4.5

[Spells."irons_spellbooks:wither_skull"]
Enabled = true
School = "irons_spellbooks:blood"
MaxLevel = 10
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 0.6

[Spells."irons_spellbooks:ascension"]
Enabled = true
School = "irons_spellbooks:lightning"
MaxLevel = 10
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 4.0

[Spells."irons_spellbooks:lightning_lance"]
Enabled = true
School = "irons_spellbooks:lightning"
MaxLevel = 10
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 2.8

[Spells."irons_spellbooks:electrocute"]
Enabled = true
School = "irons_spellbooks:lightning"
MaxLevel = 10
MinRarity = "COMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 3.0

[Spells."irons_spellbooks:lightning_bolt"]
Enabled = true
School = "irons_spellbooks:lightning"
MaxLevel = 10
MinRarity = "EPIC"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 5.7

[Spells."irons_spellbooks:charge"]
Enabled = true
School = "irons_spellbooks:lightning"
MaxLevel = 3
MinRarity = "RARE"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 8.9

[Spells."irons_spellbooks:chain_lightning"]
Enabled = true
School = "irons_spellbooks:lightning"
MaxLevel = 10
MinRarity = "UNCOMMON"
ManaCostMultiplier = 1.0
SpellPowerMultiplier = 1.0
CooldownInSeconds = 4.3
