
[Aggrobait]
	#Higher levels of Baiting will work all lower levels
	"Inclusive Tiers" = true
	#The Level that aggrobait will apply
	"Bait Level" = 5.0
	"Scale bait level" = true
	"Bait Cooldown" = 60.0
	"Bait Range" = 64.0

