ADD_TARGETS_ENABLED = true
CANNIBALISM_ENABLED = true

["Vanilla Mobs"]
	SPIDER_ENABLED = true

["Alexs Mobs"]
	ANACONDA_ENABLED = true
	BONE_SERPENT_ENABLED = true
	CACHALOT_ENABLED = true
	CAVE_CENTIPEDE_ENABLED = true
	CROW_ENABLED = true
	DROPBEAR_ENABLED = true
	EMU_ENABLED = true
	FARSEER_ENABLED = true
	FRILLED_SHARK_ENABLED = true
	GELADA_MONKEY_ENABLED = true
	GORILLA_ENABLED = true
	GRIZZLY_BEAR_ENABLED = true
	HAMMERHEAD_ENABLED = true
	MUDSKIPPER_ENABLED = true
	ORCA_ENABLED = true
	POTOO_ENABLED = true
	RACCOON_ENABLED = true
	RATTLESNAKE_ENABLED = true
	ROADRUNNER_ENABLED = true
	SHOEBILL_ENABLED = true
	STRADDLER_ENABLED = true
	TASMANIAN_DEVIL_ENABLED = true
	CAPUCHIN_ENABLED = true

