
[mobs]

	[mobs.creeper]
		#Creeper explosions have a weaker power
		"Creeper explosion nerf" = false
		#How much weaker Creeper explosions are
		#Range: 0.0 ~ 1.7976931348623157E308
		"Creeper explosion nerf factor" = 0.8

	[mobs.deeper]
		#Range: -64 ~ 320
		"Deeper max spawn height" = 60

	[mobs.peeper]
		#Range: -64 ~ 320
		"Peeper max spawn height" = -4

	[mobs.evendeeper]
		#Range: -64 ~ 320
		"Evendeeper max spawn height" = -4

	[mobs.grazer]
		#Range: -64 ~ 320
		"Grazer max spawn height" = -4

[tweaks]
	#Chainmail armor increases the user's attack damage
	"Chainmail armor increases damage" = true
	#Golden armor increases the user's movement speed
	"Golden armor increases speed" = true

	[tweaks.rails]
		#Rails can be placed in the direction you're looking at by clicking on another rail, similar to scaffolding
		"Better rail placement" = true
		#The range in blocks that better rail placement can reach
		#Range: > 0
		"Placement range" = 7

	[tweaks.trims]
		#Prevents replacing/applying a Trim Template & Material over a previously trimmed item
		#This is to prevent the player from wasting materials that could be returned at a Dismantling Table
		"Prevent replacing trims" = false

[blocks]

	[blocks.fragile_stone]
		#If ores next to or within Fragile Stone and Deepslate fall when the neighbor blocks crumble
		"Fragile stone collapses ores" = true

[items]

	[items.zirconia]
		#If Zirconia can be used as a universal repair material
		"Zirconia universal repairing" = true

