
[general]
	#The range from an active beacon where no champions will spawn (0 to disable)
	#Range: 0 ~ 1000
	beaconProtectionRange = 64
	#Set to true to enable champions from mob spawners
	championSpawners = false
	#The minimum tier of champions that will have death messages sent out upon defeat (0 to disable)
	#Range: > 0
	deathMessageTier = 0
	#A list of dimension names that are blacklisted/whitelisted for champions
	dimensionList = []
	#Set whether the dimension list is a blacklist or whitelist
	#Allowed Values: BLACKLIST, WHITELIST
	dimensionPermission = "BLACKLIST"
	#A list of entities that are blacklisted/whitelisted for champions
	entitiesList = ["blue_skies:artificial_golem", "blue_skies:spewter", "blue_skies:snow_owl", "blue_skies:nested_spider", "iceandfire:fire_dragon", "iceandfire:fire_dragon", "iceandfire:ice_dragon", "iceandfire:lightning_dragon", "iceandfire:hydra", "twilightforest:armored_giant", "alexsmobs:void_worm", "undergarden:forgotten_guardian", "cataclysm:ignis", "cataclysm:ender_golem", "cataclysm:ender_guardian", "cataclysm:netherite_monstrosity", "blue_skies:summoner", "blue_skies:alchemist", "blue_skies:starlit_crusher", "blue_skies:arachnarch", "botania:pink_wither", "botania:doppleganger", "meetyourfight:bellringer", "meetyourfight:dame_fortuna", "meetyourfight:swampjaw", "meetyourfight:bellringer", "meetyourfight:rosalyne", "meetyourfight:rose_spirit", "mowziesmobs:ferrous_wroughtnaut", "mowziesmobs:umvuthi", "mowziesmobs:frostmaw", "ars_nouveau:wilden_boss", "aquamirae:maze_mother", "aquamirae:captain_cornelia", "mowziesmobs:ferrous_wroughtnaut", "mowziesmobs:frostmaw", "mowziesmobs:umvuthi", "minecraft:vex", "lost_aether_content:aerwhale_king", "aether:valkyrie_queen", "aether:sun_spirit", "aether:slider", "minecells:concierge", "minecells:conjunctivius", "minecells:sewers_tentacle", "mowziesmobs:umvuthana_crane", "mowziesmobs:umvuthana_raptor", "bosses_of_mass_destruction:lich", "bosses_of_mass_destruction:obsidilith", "bosses_of_mass_destruction:void_blossom", "bosses_of_mass_destruction:gauntlet", "alexscaves:forsaken", "alexscaves:tremorzilla", "alexscaves:tremorsaurus", "alexscaves:hullbreaker", "graveyard:lich", "graveyard:ghoul", "cataclysm:the_prowler", "cataclysm:the_harbinger", "cataclysm:ancient_remnant", "cataclysm:the_leviathan", "cataclysm:kobolediator", "cataclysm:wadjet", "cataclysm:maledictus", "cataclysm:aptrgangr", "irons_spellbooks:dead_king", "irons_spellbooks:dead_king_corpse", "irons_spellbooks:summoned_polar_bear", "irons_spellbooks:summoned_skeleton", "irons_spellbooks:summoned_vex", "irons_spellbooks:summoned_zombie", "conjurer_illager:conjurer", "galosphere:berserker", "galosphere:preserved"]
	#Set whether the entities list is a blacklist or whitelist
	#Allowed Values: BLACKLIST, WHITELIST
	entitiesPermission = "BLACKLIST"
	#Set to true to show HUD display for champions, including health, affixes, and tier
	showHud = true
	#Set entity id (for example, ['minecraft:end_dragon', 'minecraft:creeper']) to hidden HUD display for champions, including health, affixes, and tier
	bossBarBlackList = []
	#Set to true to have champions generate a colored particle effect indicating their rank
	showParticles = true
	#Set to true to show champion tier and affixes in The One Probe overlay
	enableTOPIntegration = true
	#Enable debug for game testing
	enableDebug = false
	#Set to true to enable champions entity allow list configuration by datapack
	allowChampionsList = true
	#The permission of champions entity allow list datapack.
	#Allowed Values: BLACKLIST, WHITELIST
	allowChampionsPermission = "WHITELIST"

