#Toggle baby mob item dropping
babiesDropItems = true
#Determines how often the item will drop from a mob
#Range: > 6000
dropChance = 26000

#Sets configured mobs to drop set items
[mobDrops]
	"minecraft:chicken" = "minecraft:feather"

