
[enchantability]
	#how much each point of enchantability in the item will add to its enchantment point pool
	#Range: 0.0 ~ 1.7976931348623157E308
	"points per enchantability" = 0.5
	#if the number of enchantment points falls within this distance to a whole number, it will be rounded to the whole number instead. This allows you to have clean 1/3 or 1/7 for the incremental cost of enchantments.
	#Range: 0.0 ~ 1.0
	granularity = 0.1
	#how many enchantment points an item starts with
	#Range: 0.0 ~ 1.7976931348623157E308
	"base points" = 10.0
	#the default cost to add a new enchantment onto an item.
	#Range: 0.0 ~ 1.7976931348623157E308
	"base cost" = 0.0
	#the default cost to add one level to any existing enchantment on the item. An enchantment with level 1 will apply both the base cost and the incremental cost, once each.
	#Range: 0.0 ~ 1.7976931348623157E308
	"incremental cost" = 1.0
	#Items that have their own enchantment point cap. Format is name, base enchantability, increment per extra point of enchantability.
	"custom items" = ["minecraft:fishing_rod, 16, 0", "minecraft:bow, 15, 1", "minecraft:enchanted_book, 30, 0", "minecraft:crossbow, 15, 1", "minecraft:trident, 14, 1", "supplementaries:slingshot, 12, 0", "cataclysm:bulwark_of_the_flame, 14, 0", "blue_skies:bluebright_spear, 19, 0", "blue_skies:starlit_spear, 19, 0", "blue_skies:frostbright_spear, 19, 0", "blue_skies:lunar_spear, 19, 0", "blue_skies:dusk_spear, 19, 0", "blue_skies:maple_spear, 19, 0", "blue_skies:comet_spear, 19, 0", "blue_skies:soulbound_spear, 19, 0", "meetyourfight:twilights_thorn, 40, 0"]
	#It's really irritating how nightconfig doesn't keep the entries in separate lines, but alas. Define enchantments here. Format is name, base cost, incremental cost.
	enchantments = ["minecraft:mending, 0, 0", "ensorcellation:soulbound, 0, 0", "minecraft:infinity, 0, 1", "minecraft:unbreaking, 0, 0", "ensorcellation:vitality, 0, 1.5", "minecraft:flame, 0, 2", "minecraft:multishot, 0, 2", "enderio:withering, 0, 2", "majruszsenchantments:death_wish, 0, 2", "majruszsenchantments:dodge, 0, 1.5", "majruszsenchantments:fuse_cutter, 0, 2", "majruszsenchantments:hunter, 0, 1.5", "majruszsenchantments:immortality, 0, 8", "ensorcellation:volley, 0, 2", "allurement:reforming, 0, 0", "celestisynth:pulsation, 0, 1.5", "minecraft:fire_protection, 0, 0.5", "minecraft:blast_protection, 0, 0.5", "minecraft:projectile_protection, 0, 0.5", "ensorcellation:magic_protection, 0, 0.25", "supplementaries:lumisene_flame, 0, 2", "minecraft:soul_flame, 0, 2"]

