
[enchantability]
	#how much each point of enchantability in the item will add to its enchantment point pool
	#Range: 0.0 ~ 1.7976931348623157E308
	"points per enchantability" = 0.5
	#if the number of enchantment points falls within this distance to a whole number, it will be rounded to the whole number instead. This allows you to have clean 1/3 or 1/7 for the incremental cost of enchantments.
	#Range: 0.0 ~ 1.0
	granularity = 0.1
	#how many enchantment points an item starts with
	#Range: 0.0 ~ 1.7976931348623157E308
	"base points" = 12.0
	#the default cost to add a new enchantment onto an item.
	#Range: 0.0 ~ 1.7976931348623157E308
	"base cost" = 0.0
	#the default cost to add one level to any existing enchantment on the item. An enchantment with level 1 will apply both the base cost and the incremental cost, once each.
	#Range: 0.0 ~ 1.7976931348623157E308
	"incremental cost" = 1.0
	#Items that have their own enchantment point cap. Format is name, base enchantability, increment per extra point of enchantability.
	"custom items" = ["minecraft:fishing_rod, 16, 0", "minecraft:bow, 15, 1", "minecraft:enchanted_book, 30, 0", "minecraft:crossbow, 15, 1", "minecraft:trident, 14, 1", "supplementaries:slingshot, 12, 0", "cataclysm:bulwark_of_the_flame, 14, 0", "blue_skies:bluebright_spear, 19, 0", "blue_skies:starlit_spear, 19, 0", "blue_skies:frostbright_spear, 19, 0", "blue_skies:lunar_spear, 19, 0", "blue_skies:dusk_spear, 19, 0", "blue_skies:maple_spear, 19, 0", "blue_skies:comet_spear, 19, 0", "blue_skies:soulbound_spear, 19, 0", "meetyourfight:twilights_thorn, 40, 0"]
	#It's really irritating how nightconfig doesn't keep the entries in separate lines, but alas. Define enchantments here. Format is name, base cost, incremental cost.
	enchantments = ["minecraft:mending, 0, 0", "ensorcellation:soulbound, 0, 0", "minecraft:infinity, 1, 0", "minecraft:unbreaking, 0, 0", "minecraft:sharpness, 1.5, 0", "minecraft:protection, 1.5, 0", "ensorcellation:vitality, 1.5, 0", "minecraft:flame, 2, 0", "minecraft:power, 1.5, 0", "enigmaticlegacy:sharpshooter, 1.5, 0", "minecraft:multishot, 2, 0", "enderio:withering, 1.5, 0", "majruszsenchantments:death_wish, 1.5, 0", "majruszsenchantments:dodge, 1.5, 0", "majruszsenchantments:fuse_cutter, 2, 0", "majruszsenchantments:hunter, 1.5, 0", "majruszsenchantments:immortality, 8, 0", "feathers:lightweight, 1.5, 0", "enigmaticlegacy:wrath, 1.5, 0", "ensorcellation:volley, 2, 0"]

