
[enchantability]
	#how much each point of enchantability in the item will add to its enchantment point pool
	#Range: 0.0 ~ 1.7976931348623157E308
	"points per enchantability" = 1.0
	#if the number of enchantment points falls within this distance to a whole number, it will be rounded to the whole number instead. This allows you to have clean 1/3 or 1/7 for the incremental cost of enchantments.
	#Range: 0.0 ~ 1.0
	granularity = 0.1
	#how many enchantment points an item starts with
	#Range: 0.0 ~ 1.7976931348623157E308
	"base points" = 12.0
	#the default cost to add a new enchantment onto an item.
	#Range: 0.0 ~ 1.7976931348623157E308
	"base cost" = 0.0
	#the default cost to add one level to any existing enchantment on the item. An enchantment with level 1 will apply both the base cost and the incremental cost, once each.
	#Range: 0.0 ~ 1.7976931348623157E308
	"incremental cost" = 1.0
	#Items that have their own enchantment point cap. Format is name, base enchantability, increment per extra point of enchantability.
	"custom items" = ["minecraft:fishing_rod, 20, 0.5", "minecraft:bow, 15, 1", "minecraft:enchanted_book, 30, 0"]
	#It's really irritating how nightconfig doesn't keep the entries in separate lines, but alas. Define enchantments here. Format is name, base cost, incremental cost.
	enchantments = ["minecraft:mending, 5, 0", "minecraft:sharpness, 0, 1"]

