
#Config for EpicSamurai Mod
[epicsamurai_mod_configuration]
	#How many Aquamarine Ore Veins spawn per chunk!
	#Range: 2 ~ 10
	"Veins Per Chunk" = 2
	#How many Aquamarine Ore Blocks spawn in one Vein!
	#Range: 1 ~ 20
	"Vein Size" = 5

