
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.blue_skies]
			crystallized = false
			crescent_fruit = false
			bluebright = false
			starlit = false
			frostbright = false
			lunar = false
			dusk = false
			maple = false
			comet = false

		[types.leaves_type.naturesaura]
			ancient = true
			golden = true

		[types.leaves_type.undergarden]
			smogstem = false
			wigglewood = false
			grongle = false

		[types.leaves_type.outer_end]
			azure = true

		[types.leaves_type.thermal]
			rubberwood = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.integrateddynamics]
			menril = true

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.leaves_type.eidolon]
			illwood = true

		[types.leaves_type.aether]
			skyroot = false
			golden_oak = false
			crystal = false
			crystal_fruit = false
			holiday = false
			decorated_holiday = false

		[types.leaves_type.deep_aether]
			roseroot = false
			flowering_roseroot = false
			blue_roseroot = false
			flowering_blue_roseroot = false
			yagroot = false
			cruderoot = false
			conberry = false
			sunroot = false

		[types.leaves_type.aether_redux]
			blightwillow = false
			glacia = false
			purple_glacia = false
			gilded_oak = false
			blighted_skyroot = false
			fieldsproot = false

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.forbidden_arcanus]
			aurum = true
			nuggety_aurum = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.architects_palette]
			twisted = true

		[types.leaves_type.occultism]
			otherworld = true

		[types.leaves_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true
			palo_verde = true
			araucaria = true
			ripe_baobab = true
			flowering_baobab = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			ripe_orchard = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			yucca = true
			ripe_yucca = true
			flowering_yucca = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			silver_maple = true
			green_apple_skyris = true
			flowering_skyris = true
			flowering_ironwood = true
			white_sakura = true
			yellow_sakura = true
			yellow_birch = true
			yellow_spruce = true
			firecracker = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.traverse]
			red_autumnal = true
			brown_autumnal = true
			orange_autumnal = true
			yellow_autumnal = true
			fir = true

		[types.leaves_type.betternether]
			willow = true
			rubeus = true
			anchor_tree = true
			nether_sakura = true

		[types.leaves_type.minecells]
			wilted = true
			orange_wilted = true
			red_wilted = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

	[types.cake]

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

		[types.cake.thermal]
			chocolate_cake = true
			potion_cake = true
			spice_cake = true

		[types.cake.blue_skies]
			comet_berry_pie = true

		[types.cake.enigmaticlegacy]
			cosmic_cake = true

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

	[types.wood_type]

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.blue_skies]
			crystallized = false
			bluebright = false
			starlit = false
			frostbright = false
			lunar = false
			dusk = false
			maple = false
			comet = false

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.undergarden]
			smogstem = false
			wigglewood = false
			grongle = false

		[types.wood_type.outer_end]
			azure = true

		[types.wood_type.betterarcheology]
			rotten = true

		[types.wood_type.thermal]
			rubberwood = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.wood_type.eidolon]
			illwood = true

		[types.wood_type.aether]
			skyroot = false

		[types.wood_type.deep_aether]
			roseroot = false
			yagroot = false
			cruderoot = false
			conberry = false
			sunroot = false

		[types.wood_type.aether_redux]
			fieldsproot = false
			blightwillow = false
			cloudcap = false
			jellyshroom = false
			crystal = false
			glacia = false

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.forbidden_arcanus]
			aurum = true
			edelwood = true
			fungyss = true

		[types.wood_type.architects_palette]
			twisted = true

		[types.wood_type.naturesaura]
			ancient = true

		[types.wood_type.integrateddynamics]
			menril = true

		[types.wood_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

		[types.wood_type.betternether]
			anchor_tree = true
			mushroom_fir = true
			nether_sakura = true
			rubeus = true
			stalagnate = true
			wart = true
			willow = true
			nether_reed = true
			nether_mushroom = true

		[types.wood_type.traverse]
			fir = true

		[types.wood_type.minecells]
			putrid = true

		[types.wood_type.endergetic]
			poise = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.architects_palette]
			board_stairs = true
			railing = true
			boards = true
			board_slab = true
			board_wall = true

		[entries.wood_type.vct]
			crafting_table = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.mcwroofs]
			planks_upper_steep_roof = true
			top_roof = true
			lower_roof = true
			planks_roof = true
			upper_steep_roof = true
			steep_roof = true
			roof = true
			planks_attic_roof = true
			upper_lower_roof = true
			planks_top_roof = true
			planks_steep_roof = true
			attic_roof = true
			planks_upper_lower_roof = true
			planks_lower_roof = true

		[entries.wood_type.another_furniture]
			shelf = true
			bench = true
			flower_box = true
			shutter = true
			table = true
			drawer = true
			chair = true

		[entries.wood_type.mcwwindows]
			plank_window = true
			louvered_shutter = true
			plank_window2 = true
			pane_window = true
			plank_pane_window = true
			stripped_pane_window = true
			plank_four_window = true
			stripped_log_window2 = true
			log_parapet = true
			window2 = true
			stripped_log_four_window = true
			four_window = true
			plank_parapet = true
			blinds = true
			window = true
			shutter = true
			stripped_log_window = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge_stair = true
			log_bridge_stair = true
			rail_bridge = true
			rope_bridge = true
			log_bridge_middle = true

		[entries.wood_type.quark]
			vertical_planks = true
			chest = true
			ladder = true
			hollow_log = true
			post = true
			trapped_chest = true
			bookshelf = true
			stripped_post = true
			vertical_slab = true

		[entries.wood_type.farmersdelight]
			cabinet = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

