
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	#Disables certain types
	[general.types]

		[general.types.leaves_type]

			[general.types.leaves_type.ars_nouveau]
				blue_archwood = true
				green_archwood = true
				purple_archwood = true
				red_archwood = true

			[general.types.leaves_type.blue_skies]
				crystallized = true
				crescent_fruit = true
				bluebright = true
				starlit = true
				frostbright = true
				lunar = true
				dusk = true
				maple = true
				comet = true

			[general.types.leaves_type.minecells]
				wilted = true
				orange_wilted = true
				red_wilted = true

			[general.types.leaves_type.wilderwild]
				baobab = true
				cypress = true

			[general.types.leaves_type.naturesaura]
				ancient = true
				golden = true

			[general.types.leaves_type.quark]
				ancient = true
				blue_blossom = true
				lavender_blossom = true
				orange_blossom = true
				yellow_blossom = true
				red_blossom = true

			[general.types.leaves_type.thermal]
				rubberwood = true

			[general.types.leaves_type.ars_elemental]
				yellow_archwood = true

			[general.types.leaves_type.eidolon]
				illwood = true

			[general.types.leaves_type.aether]
				skyroot = true
				golden_oak = true
				crystal = true
				crystal_fruit = true
				holiday = true
				decorated_holiday = true

			[general.types.leaves_type.deeperdarker]
				echo = true

			[general.types.leaves_type.alexscaves]
				ancient = true

			[general.types.leaves_type.forbidden_arcanus]
				aurum = true
				nuggety_aurum = true

			[general.types.leaves_type.ecologics]
				coconut = true
				walnut = true

			[general.types.leaves_type.integrateddynamics]
				menril = true

			[general.types.leaves_type.betternether]
				willow = true
				rubeus = true
				anchor_tree = true
				nether_sakura = true

			[general.types.leaves_type.betterend]
				pythadendron = true
				lacugrove = true
				dragon_tree = true
				tenanea = true
				lucernia = true

			[general.types.leaves_type.upgrade_aquatic]
				river = true

			[general.types.leaves_type.autumnity]
				maple = true
				yellow_maple = true
				orange_maple = true
				red_maple = true

			[general.types.leaves_type.architects_palette]
				twisted = true

			[general.types.leaves_type.undergarden]
				smogstem = true
				wigglewood = true
				grongle = true

			[general.types.leaves_type.traverse]
				red_autumnal = true
				brown_autumnal = true
				orange_autumnal = true
				yellow_autumnal = true
				fir = true

			[general.types.leaves_type.hexerei]
				mahogany = true
				willow = true
				witch_hazel = true

		[general.types.cake]

			[general.types.cake.createaddition]
				chocolate_cake = true
				honey_cake = true

			[general.types.cake.thermal]
				chocolate_cake = true
				potion_cake = true
				spice_cake = true

			[general.types.cake.blue_skies]
				comet_berry_pie = true

			[general.types.cake.enigmaticlegacy]
				cosmic_cake = true

			[general.types.cake.neapolitan]
				vanilla_cake = true
				chocolate_cake = true
				strawberry_cake = true
				banana_cake = true
				mint_cake = true
				adzuki_cake = true

		[general.types.wood_type]

			[general.types.wood_type.ars_nouveau]
				archwood = true

			[general.types.wood_type.blue_skies]
				crystallized = true
				bluebright = true
				starlit = true
				frostbright = true
				lunar = true
				dusk = true
				maple = true
				comet = true

			[general.types.wood_type.quark]
				azalea = true
				ancient = true
				blossom = true

			[general.types.wood_type.minecells]
				putrid = true

			[general.types.wood_type.wilderwild]
				baobab = true
				cypress = true
				palm = true

			[general.types.wood_type.thermal]
				rubberwood = true

			[general.types.wood_type.eidolon]
				illwood = true

			[general.types.wood_type.aether]
				skyroot = true

			[general.types.wood_type.iceandfire]
				dreadwood = true

			[general.types.wood_type.deeperdarker]
				echo = true

			[general.types.wood_type.alexscaves]
				pewen = true
				thornwood = true

			[general.types.wood_type.forbidden_arcanus]
				aurum = true
				edelwood = true

			[general.types.wood_type.ecologics]
				flowering_azalea = true
				azalea = true
				coconut = true
				walnut = true

			[general.types.wood_type.betternether]
				nether_reed = true
				stalagnate = true
				willow = true
				wart = true
				rubeus = true
				mushroom_fir = true
				nether_mushroom = true
				anchor_tree = true
				nether_sakura = true

			[general.types.wood_type.betterend]
				mossy_glowshroom = true
				pythadendron = true
				end_lotus = true
				lacugrove = true
				dragon_tree = true
				tenanea = true
				helix_tree = true
				umbrella_tree = true
				jellyshroom = true
				lucernia = true

			[general.types.wood_type.upgrade_aquatic]
				driftwood = true
				river = true

			[general.types.wood_type.autumnity]
				maple = true

			[general.types.wood_type.architects_palette]
				twisted = true

			[general.types.wood_type.cataclysm]
				chorus = true

			[general.types.wood_type.undergarden]
				smogstem = true
				wigglewood = true
				grongle = true

			[general.types.wood_type.botania]
				livingwood = true
				dreamwood = true

			[general.types.wood_type.traverse]
				fir = true

			[general.types.wood_type.hexerei]
				mahogany = true
				willow = true
				witch_hazel = true

	#Disables specific entries
	[general.entries]

		[general.entries.leaves_type]

			[general.entries.leaves_type.quark]
				hedge = true
				leaf_carpet = true

			[general.entries.leaves_type.mcwfences]
				hedge = true

		[general.entries.wood_type]

			[general.entries.wood_type.quark]
				vertical_planks = true
				ladder = true
				post = true
				trapped_chest = true
				chest = true
				hollow_log = true
				bookshelf = true
				stripped_post = true

			[general.entries.wood_type.decorative_blocks]
				seat = true
				palisade = true
				beam = true
				support = true

			[general.entries.wood_type.farmersdelight]
				cabinet = true

			[general.entries.wood_type.storagedrawers]
				full_drawers_2 = true
				full_drawers_4 = true
				full_drawers_1 = true
				half_drawers_1 = true
				half_drawers_4 = true
				half_drawers_2 = true
				trim = true

			[general.entries.wood_type.create]
				window_pane = true
				window = true

			[general.entries.wood_type.mcwroofs]
				planks_upper_steep_roof = true
				top_roof = true
				lower_roof = true
				planks_roof = true
				upper_steep_roof = true
				steep_roof = true
				upper_lower_roof = true
				attic_roof = true
				planks_upper_lower_roof = true
				roof = true
				planks_attic_roof = true
				planks_top_roof = true
				planks_steep_roof = true
				planks_lower_roof = true

			[general.entries.wood_type.mcwwindows]
				louvered_shutter = true
				plank_pane_window = true
				plank_four_window = true
				stripped_log_window2 = true
				log_parapet = true
				window2 = true
				stripped_log_four_window = true
				stripped_log_window = true
				plank_window = true
				plank_window2 = true
				pane_window = true
				stripped_pane_window = true
				four_window = true
				plank_parapet = true
				blinds = true
				window = true
				shutter = true

			[general.entries.wood_type.mcwfences]
				highley_gate = true
				picket_fence = true
				stockade_fence = true
				wired_fence = true
				horse_fence = true
				pyramid_gate = true

			[general.entries.wood_type.mcwlights]
				tiki_torch = true
				soul_tiki_torch = true

			[general.entries.wood_type.mcwbridges]
				bridge_pier = true
				rope_bridge = true
				log_bridge_middle = true
				rope_bridge_stair = true
				log_bridge_stair = true
				rail_bridge = true

			[general.entries.wood_type.architects_palette]
				board_stairs = true
				board_wall = true
				railing = true
				boards = true
				board_slab = true

			[general.entries.wood_type.another_furniture]
				flower_box = true
				shutter = true
				drawer = true
				shelf = true
				bench = true
				table = true
				chair = true

