
[logbegone]
	phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "feathers", "Shield Expansion"]
	regex = ["Disconnecting VANILLA connection attempt", "Channels ", "feathers", "Shield Expansion"]

