#
#Do you like Pierogi? Yes, this is an important setting. (Default: true)
sayYesDoIt = true

#(Only Fight or Flight) Common Configurations
["Time Adjustments"]
	#
	#Change the time set in-combat when player is ATTACKING. (Default: 200 in ticks)
	timeByAttacking = 60
	#
	#Change the time set in-combat when player is being DAMAGED. (Default: 400 in ticks)
	timeByDamaged = 120
	#
	#Change the time set in-combat when player is being TARGETED by a mob. (Default: 300 in ticks)
	timeByTargeted = 120

["Enable/Disable Features"]
	#
	#Determine whether being targeted by a mod is considered in-combat. "true" disables it. (Default: false)
	disableAggroCombat = false
	#
	#Trigger in-combat through proximity with mobs instead of based on aggro. Recommended to use with Mob Blacklist. (Default: false)
	enableByProximity = false

["Allowed/Disallowed Settings"]
	#
	#Allow certain blocks to be placed regardless if player is in combat. (If blockBlacklist has any valid entries, this list is ignored)
	#Example: 
	# blockWhitelist = [
	# 	"minecraft:dirt",
	# 	"minecraft:crafting_table",
	# 	"minecraft:glass"
	# ]
	#
	blockWhitelist = ["minecraft:torch", "minecraft:redstone_torch", "minecraft:soul_torch", "minecraft:lantern", "minecraft:soul_lantern", "minecraft:cobweb"]
	#
	#Deny certain blocks to be placed if player is in combat. This will cause every other block to be placeable regardless if player is in combat.
	#Example: 
	# blockBlacklist = [
	# 	"minecraft:sand",
	# 	"minecraft:gravel",
	# 	"modid:something_block"
	# ]
	#
	blockBlacklist = []
	#
	#Allow certain mobs/entities to not trigger in-combat regardless if player attacks or is attacked by them. (If mobBlacklist has any valid entries, this list is ignored)
	#Written the same as blockWhitelist.
	#
	mobWhitelist = []
	#
	#Make only certain mobs/entities trigger in-combat effects. This will cause all other mobs/entities
	#to never trigger combat effects regardless if you attack them or been attacked by them.
	#Written the same as blockBlacklist.
	#
	mobBlacklist = ["dummmmmmy:target_dummy"]

[Performance]
	#
	#Change how often each player gets checked for any surrounding mobs targeting them. (Default: 60 in ticks)
	#Be careful not to set this too low as it may cause performance issues!
	updateInterval = 60
	#
	#Change the radius of the check for surrounding mobs. (Default: 16 in blocks)
	#Don't make this too high!
	radiusCheck = 16

