
[world]
	# Default world settings. These will apply to newly-generated worlds only, existing worlds will remember their own settings.
	#
	# The average size of each temperature band in blocks.
	# Vanilla Minecraft generation has 5 temperature zones - Freezing, Cool, Temperate, Warm and Hot - every biome fits into one of these five temperature ranges.
	# So for example, if this value is 2048, the distance from the *center* of one one Hot band to the next Hot band center will be about 16384 (2048 * 8) blocks (Hot through to Freezing and back again).
	# If there are any worldgen mods that add biomes with a different 'temperature range' for placement, they should be incorporated within existing bands normally.
	#Range: 512 ~ 32768
	bandSize = 2048
	# If true, bands will be vertical instead of horizontal.
	useVerticalBands = false
	# Shift the bands by this percentage.
	# Normally the Hot band (Desert and such) will generate at origin (0,0) so the default shift of 25% will make the origin temperate (middle temp) instead, shifted
	# downwards to simulate a 'Northern hemisphere' start (Colder will be North, or East if Vertical bands, and Hotter will be South or West). A value of 0.75 would simulate southern hemisphere start instead.
	#Range: 0.0 ~ 1.0
	bandPositionShift = 0.25
	# Absolute min/max temperature range. Increasing this will make the coldest and hottest bands larger while reducing others, lowering this value will have the opposite effect.
	# The default value makes the hottest/coldest bands a tiny bit smaller than the others.
	# Be careful, setting this value too high or too low could result in some bands not generating at all.
	#Range: 0.3 ~ 1.0
	tempRange = 0.625
	# Vanilla temperature has a bias towards cold, this value is used to make the hottest and coldest roughly the same size.
	# If you set it to zero, the coldest band will be larger than all other bands and the hottest would be smaller than all others.
	# You probably wont want to change this, but I made it configurable anyway.
	#Range: -0.5 ~ 0.5
	tempGradeShift = -0.05
	# Algorithm to use. You can configure and read more about each algorithm in their own section below. Recommended to use World Preview if you want to change things around.
	# Note: There is only 1 algorithm currently, this config is here just in case I add more later.
	#Range: 1 ~ 1
	bandAlgorithm = 1
	# If above zero, will use original noise generation to help make the edges between bands a bit nicer.
	# See each algorithm for details on how noiseFactor is used.
	# The unit is arbitrary and very dependent on bandSize. For e.g. 100 is nice for a bandSize of 2048 but might be too wild if bandSize is decreased, or too tame if bandSize is increased.
	#Range: 0 ~ 1000
	noiseFactor = 100

[algorithm1]
	# Settings for algorithm 1, the 'simple' or 'default' algorithm.
	# This algorithm is very simple and produces jaggy lines that aren't very random or natural looking, but it looks OK as long as you keep useNoise enabled.
	# Keeping the variance low but noiseFactor a decent amount (around 100 or so) will produce some OK looking curves/waves in the bands, but it you want something more predictable you can reduce noiseFactor and increase variance.
	#
	# Band variance in blocks (roughly). If below 10, each band will have a completely straight edge across the world and disables all remaining algo1 features.
	# You will want to keep this a fairly small value. Making it too large could result in weirdness, especially if it's too close to the bandSize.
	#Range: 0 ~ 16384
	bandVariance = 32
	# Steepness of band variance. Unit is arbitrary, you'll want to experiment and test if you change it. Probably best left alone though.
	#Range: 0.1 ~ 10.0
	algo1bandVarianceSteepness = 0.2

