
[blocks]
	Sawmill = true
	"Wooden boards" = true
	"Wooden bookshelves" = false
	"Wooden ladders" = false
	"Wooden beehives" = true
	"Wooden chests" = false
	"Leaf piles" = true

[generation]
	#If variant bookshelves replace bookshelves in Villages
	"Wooden bookshelves in Villages" = true
	#If variant ladders replace ladders in Villages
	"Wooden ladders in Villages" = true
	#If variant chests replace chests in Villages
	"Wooden chests in Villages" = true

