[general]
enabled = true
cost = 200
starter = false
per_spell_limit = 3
glyph_tier = 2
augment_limits = [ "ars_nouveau:glyph_amplify=2",]
augment_cost_overrides = []
invalid_combos = []
amplify = 0.5
base = 0.75
aoe_bonus = 1.5
damage = 6.0
amp_damage = 2.5
