[general]
enabled = true
cost = 100
starter = false
per_spell_limit = 3
glyph_tier = 3
augment_limits = [ "ars_nouveau:glyph_amplify=2",]
augment_cost_overrides = []
invalid_combos = []
damage = 5.0
amplify = 3.0
wet_bonus = 2.0
