[general]
enabled = true
cost = 30
starter = false
per_spell_limit = 3
glyph_tier = 2
augment_limits = [ "ars_nouveau:glyph_aoe=1", "ars_nouveau:glyph_extend_time=1",]
augment_cost_overrides = []
invalid_combos = []
