[general]
enabled = true
cost = 0
starter = false
per_spell_limit = 3
glyph_tier = 1
augment_limits = [ "ars_nouveau:glyph_amplify=2",]
augment_cost_overrides = []
invalid_combos = []
damage = 1.0
amplify = 1.0
