[general]
enabled = true
cost = 15
starter = true
per_spell_limit = 3
glyph_tier = 1
augment_limits = [ "ars_nouveau:glyph_amplify=2",]
augment_cost_overrides = []
invalid_combos = []
damage = 5.0
amplify = 2.0
potion_time = 5
extend_time = 5
