[general]
enabled = true
cost = 100
starter = false
per_spell_limit = 3
glyph_tier = 3
augment_limits = [ "ars_nouveau:glyph_amplify=4",]
augment_cost_overrides = []
invalid_combos = []
potion_time = 30
extend_time = 8
