[general]
enabled = true
cost = 15
starter = false
per_spell_limit = 3
glyph_tier = 1
augment_limits = [ "ars_nouveau:glyph_sensitive=1",]
augment_cost_overrides = []
invalid_combos = []
potion_time = 10
extend_time = 5
