[general]
enabled = true
cost = 25
starter = false
per_spell_limit = 3
glyph_tier = 1
augment_limits = []
augment_cost_overrides = []
invalid_combos = []
force_ground = false
knock_up = 1.5
amplify = 1.0
