[general]
enabled = true
cost = 30
starter = false
per_spell_limit = 3
glyph_tier = 2
augment_limits = []
augment_cost_overrides = []
invalid_combos = []
potion_time = 30
extend_time = 8
charm_hp_limit = 150
