[general]
enabled = true
cost = 25
starter = false
per_spell_limit = 3
glyph_tier = 2
augment_limits = [ "ars_nouveau:glyph_amplify=2",]
augment_cost_overrides = []
invalid_combos = []
potion_time = 30
extend_time = 8
damage = 5.0
amplify = 2.0
