
#HUD settings
[HUD]
	#Use Graphical Meters
	useGraphicalMeters = true
	#Chat message when toggling module
	toggleModuleSpam = false
	#Display HUD
	keybind_HUD_on = true
	#x position
	#Range: 0.0 ~ 1.7976931348623157E308
	keybindHUDx = 8.0
	#x position
	#Range: 0.0 ~ 1.7976931348623157E308
	keybindHUDy = 60.0
	#Use a 24h clock instead of 12h
	use24hClock = false

["Meter Settings"]
	#Show meters when paused
	# Useful for trying different colors in real time
	showMetersWhenPaused = false

	["Meter Settings"."Heat Meter Settings"]
		#value to manually set the meter at.
		# Useful for trying different colors in real time
		#Range: 0.0 ~ 100.0
		heatMeterDebugValue = 0.0
		#hud heat meter glass red color amount (0 - 100)
		#Range: 0 ~ 100
		heatMeterGlassRedPercent = 100
		#hud heat meter glass green color amount (0 - 100)
		#Range: 0 ~ 100
		heatMeterGlassGreenPercent = 100
		#hud heat meter glass blue color amount (0 - 100)
		#Range: 0 ~ 100
		heatMeterGlassBluePercent = 100
		#hud heat meter glass alpha color amount (0 - 100)
		#Range: 0 ~ 100
		heatMeterGlassAlphaPercent = 85
		#hud heat meter bar red color amount (0 - 100)
		#Range: 0 ~ 100
		heatMeterBarRedPercent = 100
		#hud heat meter bar green color amount (0 - 100)
		#Range: 0 ~ 100
		heatMeterBarGreenPercent = 100
		#hud heat meter bar blue color amount (0 - 100)
		#Range: 0 ~ 100
		heatMeterBarBluePercent = 100
		#hud heat meter bar alpha color amount (0 - 100)
		#Range: 0 ~ 100
		heatMeterBarAlphaPercent = 85

	["Meter Settings"."Energy Meter Settings"]
		#value to manually set the meter at.
		# Useful for trying different colors in real time
		#Range: 0.0 ~ 100.0
		energyMeterDebugValue = 0.0
		#hud energy meter glass red color amount (0 - 100)
		#Range: 0 ~ 100
		energyMeterGlassRedPercent = 100
		#hud energy meter glass green color amount (0 - 100)
		#Range: 0 ~ 100
		energyMeterGlassGreenPercent = 100
		#hud energy meter glass blue color amount (0 - 100)
		#Range: 0 ~ 100
		energyMeterGlassBluePercent = 100
		#hud energy meter glass alpha color amount (0 - 100)
		#Range: 0 ~ 100
		energyMeterGlassAlphaPercent = 85
		#hud energy meter bar red color amount (0 - 100)
		#Range: 0 ~ 100
		energyMeterBarRedPercent = 20
		#hud energy meter bar green color amount (0 - 100)
		#Range: 0 ~ 100
		energyMeterBarGreenPercent = 90
		#hud energy meter bar blue color amount (0 - 100)
		#Range: 0 ~ 100
		energyMeterBarBluePercent = 30
		#hud energy meter bar alpha color amount (0 - 100)
		#Range: 0 ~ 100
		energyMeterBarAlphaPercent = 85

	["Meter Settings"."Weapon Charge Meter Settings"]
		#value to manually set the meter at.
		# Useful for trying different colors in real time
		#Range: 0.0 ~ 100.0
		weaponChargeMeterDebugValue = 0.0
		#hud weapon charge meter glass red color amount (0 - 100)
		#Range: 0 ~ 100
		weaponChargeMeterGlassRedPercent = 100
		#hud weapon charge meter glass green color amount (0 - 100)
		#Range: 0 ~ 100
		weaponChargeMeterGlassGreenPercent = 100
		#hud weapon charge meter glass blue color amount (0 - 100)
		#Range: 0 ~ 100
		weaponChargeMeterGlassBluePercent = 100
		#hud weapon charge meter glass alpha color amount (0 - 100)
		#Range: 0 ~ 100
		weaponChargeMeterGlassAlphaPercent = 85
		#hud weapon charge meter bar red color amount (0 - 100)
		#Range: 0 ~ 100
		weaponChargeMeterBarRedPercent = 80
		#hud weapon charge meter bar green color amount (0 - 100)
		#Range: 0 ~ 100
		weaponChargeMeterBarGreenPercent = 60
		#hud weapon charge meter bar blue color amount (0 - 100)
		#Range: 0 ~ 100
		weaponChargeMeterBarBluePercent = 100
		#hud weapon charge meter bar alpha color amount (0 - 100)
		#Range: 0 ~ 100
		weaponChargeMeterBarAlphaPercent = 85

	["Meter Settings"."Water Meter Settings"]
		#value to manually set the meter at.
		# Useful for trying different colors in real time
		#Range: 0.0 ~ 100.0
		waterMeterDebugValue = 0.0
		#hud water meter glass red color amount (0 - 100)
		#Range: 0 ~ 100
		waterMeterGlassRedPercent = 100
		#hud water meter glass green color amount (0 - 100)
		#Range: 0 ~ 100
		waterMeterGlassGreenPercent = 100
		#hud water meter glass blue color amount (0 - 100)
		#Range: 0 ~ 100
		waterMeterGlassBluePercent = 100
		#hud water meter glass alpha color amount (0 - 100)
		#Range: 0 ~ 100
		waterMeterGlassAlphaPercent = 85
		#hud water meter bar red color amount (0 - 100)
		#Range: 0 ~ 100
		waterMeterBarRedPercent = 100
		#hud water meter bar green color amount (0 - 100)
		#Range: 0 ~ 100
		waterMeterBarGreenPercent = 100
		#hud water meter bar blue color amount (0 - 100)
		#Range: 0 ~ 100
		waterMeterBarBluePercent = 100
		#hud water meter bar alpha color amount (0 - 100)
		#Range: 0 ~ 100
		waterMeterBarAlphaPercent = 85

